const MenuApi = [
  {
    id: 1,
    Image: "./images/maggi.jpg",
    name: "maggi",
    category: "breakfast",
    price: 50,
    description: "gksdkfgoasdufgosdufgv  osdg odgfosdg ouasdffgou dgsdf osd",
  },
  {
    id: 2,
    Image: "./images/egg.jpg",
    name: "egg",
    category: "breakfast",
    price: 50,
    description: "gksdkfgoasdufgosdufgv  osdg odgfosdg ouasdffgou dgsdf osd",
  },
  {
    id: 3,
    Image: "https://unsplash.com/photos/SQ20tWzxXO0",
    name: "bread",
    category: "lunch",
    price: 50,
    description: "gksdkfgoasdufgosdufgv  osdg odgfosdg ouasdffgou dgsdf osd",
  },
  {
    id: 4,
    Image: "images/maggi.jpg",
    name: "maggi",
    category: "lunch",
    price: 50,
    description: "gksdkfgoasdufgosdufgv  osdg odgfosdg ouasdffgou dgsdf osd",
  },
  {
    id: 5,
    Image: "images/maggi.jpg",
    name: "cunch",
    category: "dinner",
    price: 50,
    description: "gksdkfgoasdufgosdufgv  osdg odgfosdg ouasdffgou dgsdf osd",
  },
  {
    id: 6,
    Image: "images/maggi.jpg",
    name: "maggi",
    category: "dinner",
    price: 50,
    description: "gksdkfgoasdufgosdufgv  osdg odgfosdg ouasdffgou dgsdf osd",
  },
  {
    id: 7,
    Image: "images/maggi.jpg",
    name: "maggi",
    category: "dinner",
    price: 50,
    description: "gksdkfgoasdufgosdufgv  osdg odgfosdg ouasdffgou dgsdf osd",
  },
  {
    id: 8,
    Image: "images/maggi.jpg",
    name: "maggi",
    category: "dinner",
    price: 50,
    description: "gksdkfgoasdufgosdufgv  osdg odgfosdg ouasdffgou dgsdf osd",
  },
  {
    id: 9,
    Image: "images/maggi.jpg",
    name: "maggi",
    category: "evening",
    price: 50,
    description: "gksdkfgoasdufgosdufgv  osdg odgfosdg ouasdffgou dgsdf osd",
  },
  {
    id: 10,
    Image: "images/maggi.jpg",
    name: "maggi",
    category: "evening",
    price: 50,
    description: "gksdkfgoasdufgosdufgv  osdg odgfosdg ouasdffgou dgsdf osd",
  },
  {
    id: 11,
    Image: "images/maggi.jpg",
    name: "maggi",
    category: "evening",
    price: 50,
    description: "gksdkfgoasdufgosdufgv  osdg odgfosdg ouasdffgou dgsdf osd",
  },
];

export default MenuApi;
